//please do not edit this file,it is auto created by go generate
package pprofCheck

import (
	"net/http"
)

//pprof check
func HealthHandler(w http.ResponseWriter, r *http.Request) {
	// A very simple health check.
	w.WriteHeader(http.StatusOK)
	w.Header().Set("Content-Type", "application/json")

	// In the future we could report back on the status of our DB, or our cache
	// (e.g. Redis) by performing a simple PING, and include them in the response.
	w.Write([]byte(`{"code":0,"alive": true,version:"2019-07-14 11:28"}`))
}
