//please do not edit this file,it is auto created by go generate
package routes

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func HealthCheckHandler(w http.ResponseWriter, r *http.Request) {
	// A very simple health check.
	w.WriteHeader(http.StatusOK)
	w.Header().Set("Content-Type", "application/json")

	// In the future we could report back on the status of our DB, or our cache
	// (e.g. Redis) by performing a simple PING, and include them in the response.
	w.Write([]byte(`{"code":0,"alive": true,version:"20190713 22:24"}`))
}

// gin框架健康检查
func HealthCheck(ctx *gin.Context) {
	ctx.JSON(200, map[string]interface{}{
		"code":    0,
		"alive":   true,
		"version": "20190713 22:24",
	})
}
